# ===============================
# Server Configuration
# ===============================
server.port=8080


# ===============================
# Spring Application
# ===============================
spring.application.name=backend


# ===============================
# Datasource (MSSQL)
# ===============================
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=SPLIT_WISE;trustServerCertificate=true;encrypt=false;
spring.datasource.username=sa
spring.datasource.password=Lws12345
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver


# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.format_sql=true


# ===============================
# Flyway Migration
# ===============================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration


# ===============================
# Logging
# ===============================
logging.level.org.hibernate.SQL=debug


logging.level.root=WARN
spring.main.banner-mode=off

logging.level.org.hibernate.orm.jdbc.bind=TRACE
